name: sitemap_add

on:
  repository_dispatch:
    types: [sitemap_add]
jobs:
  build:
    name: add
    runs-on: ubuntu-latest
    timeout-minutes: 180 # タイムアウト設定しないと永遠に処理走って大変になる場合がある
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: npm
    - name: Install Dependencies
      run: npm ci
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: Create Sitemap
      run: npm run add -- "${{ toJSON(github.event.client_payload).id }}"
    - name: Git Setting
      run: |
        git config --local user.email 136794662+tokokitabutsuri@users.noreply.github.com
        git config --local user.name tokokitabutsuri
    - name: Commit Sitemap
      run: |
        git add /sitemap.xml
        git commit -m "Add sitemap.xml by Github Actions"
        git pull
        git push origin